apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: hello-fastapi
  newName: marianichelle/hello-fastapi-k8s
  newTag: 657fe39ba5eea61acfa59cc3f818d537f82850d3
